# Generated by Django 4.0.4 on 2022-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='appropriate',
            field=models.CharField(choices=[('<8', 'under 8'), ('8:15', 'from 8 to 15'), ('>15', 'adult')], default='>15', max_length=250),
        ),
    ]
